-- MySQL Script generated by MySQL Workbench
-- lun. 12 avril 2021 12:08:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mini_chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mini_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mini_chat` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `mini_chat` ;

-- -----------------------------------------------------
-- Table `mini_chat`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mini_chat`.`user` ;

CREATE TABLE IF NOT EXISTS `mini_chat`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(75) NOT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_chat`.`chat_room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mini_chat`.`chat_room` ;

CREATE TABLE IF NOT EXISTS `mini_chat`.`chat_room` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_chat`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mini_chat`.`message` ;

CREATE TABLE IF NOT EXISTS `mini_chat`.`message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `date` INT UNSIGNED NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `chat_room_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `message_user_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `message_caht_room_fk_idx` (`chat_room_id` ASC) VISIBLE,
  CONSTRAINT `message_user_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mini_chat`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `message_caht_room_fk`
    FOREIGN KEY (`chat_room_id`)
    REFERENCES `mini_chat`.`chat_room` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mini_chat`.`private_messsage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mini_chat`.`private_messsage` ;

CREATE TABLE IF NOT EXISTS `mini_chat`.`private_messsage` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `user2_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `privatemessage_user1_fk_idx` (`user_id` ASC) VISIBLE,
  INDEX `private_message_user2_fk_idx` (`user2_id` ASC) VISIBLE,
  CONSTRAINT `private_message_user1_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `mini_chat`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `private_message_user2_fk`
    FOREIGN KEY (`user2_id`)
    REFERENCES `mini_chat`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
